//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class V5Entities6 : DbContext
    {
        public V5Entities6()
            : base("name=V5Entities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HCM_COUNTRY> HCM_COUNTRY { get; set; }
        public virtual DbSet<HCM_SKILLS> HCM_SKILLS { get; set; }
        public virtual DbSet<HC_RESUME_DOCUMENTS> HC_RESUME_DOCUMENTS { get; set; }
        public virtual DbSet<HCM_STATES> HCM_STATES { get; set; }
        public virtual DbSet<IHD_CO_SEARCH> IHD_CO_SEARCH { get; set; }
        public virtual DbSet<IHD_CO_SEARCH_VIEW> IHD_CO_SEARCH_VIEW { get; set; }
        public virtual DbSet<IHD_COSEARCH_REPORT> IHD_COSEARCH_REPORT { get; set; }
    
        public virtual ObjectResult<IHD_COSEARCH_GRID_Result> IHD_COSEARCH_GRID(Nullable<long> country)
        {
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_GRID_Result>("IHD_COSEARCH_GRID", countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_GRID_1_Result> IHD_COSEARCH_GRID_1(Nullable<long> country)
        {
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_GRID_1_Result>("IHD_COSEARCH_GRID_1", countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_GRID_LOC_SKILL_Result> IHD_COSEARCH_GRID_LOC_SKILL(string locationid, string skillId, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_GRID_LOC_SKILL_Result>("IHD_COSEARCH_GRID_LOC_SKILL", locationidParameter, skillIdParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_GP_Spread_Location_2_Result> IHD_GP_Spread_Location_2(Nullable<long> country)
        {
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_GP_Spread_Location_2_Result>("IHD_GP_Spread_Location_2", countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_GRID_2_Result> IHD_COSEARCH_GRID_2(Nullable<long> country)
        {
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_GRID_2_Result>("IHD_COSEARCH_GRID_2", countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_LOC_SKILL_Result> IHD_COSEARCH_LOC_SKILL(string locationid, string skillId, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_LOC_SKILL_Result>("IHD_COSEARCH_LOC_SKILL", locationidParameter, skillIdParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_Result> IHD_COSEARCH(Nullable<long> country)
        {
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_Result>("IHD_COSEARCH", countryParameter);
        }
    
        public virtual int IHD_COSEARCH_GRID_LOC_SKILL_2(string locationid, string skillId, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IHD_COSEARCH_GRID_LOC_SKILL_2", locationidParameter, skillIdParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_GRID_LOC_SKILL_3_Result> IHD_COSEARCH_GRID_LOC_SKILL_3(string locationid, string skillId, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_GRID_LOC_SKILL_3_Result>("IHD_COSEARCH_GRID_LOC_SKILL_3", locationidParameter, skillIdParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_LOC_SKILL_1_Result> IHD_COSEARCH_LOC_SKILL_1(string locationid, string skillId, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_LOC_SKILL_1_Result>("IHD_COSEARCH_LOC_SKILL_1", locationidParameter, skillIdParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_LOC_SKILL_2_Result> IHD_COSEARCH_LOC_SKILL_2(string locationid, string skillId, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_LOC_SKILL_2_Result>("IHD_COSEARCH_LOC_SKILL_2", locationidParameter, skillIdParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_1_Result> IHD_COSEARCH_1(Nullable<long> country)
        {
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_1_Result>("IHD_COSEARCH_1", countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_LOC_SKILL_3_Result> IHD_COSEARCH_LOC_SKILL_3(string locationid, string skillId, string optionalid, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var optionalidParameter = optionalid != null ?
                new ObjectParameter("optionalid", optionalid) :
                new ObjectParameter("optionalid", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_LOC_SKILL_3_Result>("IHD_COSEARCH_LOC_SKILL_3", locationidParameter, skillIdParameter, optionalidParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_2_Result> IHD_COSEARCH_2(Nullable<long> country)
        {
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_2_Result>("IHD_COSEARCH_2", countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_SKILL_MANOP_Result> IHD_COSEARCH_SKILL_MANOP(string locationid, string skillId, string optionalid, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var optionalidParameter = optionalid != null ?
                new ObjectParameter("optionalid", optionalid) :
                new ObjectParameter("optionalid", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_SKILL_MANOP_Result>("IHD_COSEARCH_SKILL_MANOP", locationidParameter, skillIdParameter, optionalidParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_SKILL_3_Result> IHD_COSEARCH_SKILL_3(string locationid, string skillId, string optionalid, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var optionalidParameter = optionalid != null ?
                new ObjectParameter("optionalid", optionalid) :
                new ObjectParameter("optionalid", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_SKILL_3_Result>("IHD_COSEARCH_SKILL_3", locationidParameter, skillIdParameter, optionalidParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_COSEARCH_SKILL_4_Result> IHD_COSEARCH_SKILL_4(string locationid, string skillId, string optionalid, Nullable<long> country)
        {
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var skillIdParameter = skillId != null ?
                new ObjectParameter("skillId", skillId) :
                new ObjectParameter("skillId", typeof(string));
    
            var optionalidParameter = optionalid != null ?
                new ObjectParameter("optionalid", optionalid) :
                new ObjectParameter("optionalid", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_COSEARCH_SKILL_4_Result>("IHD_COSEARCH_SKILL_4", locationidParameter, skillIdParameter, optionalidParameter, countryParameter);
        }
    
        public virtual ObjectResult<IHD_CANDIDATEJOURNAL_VIEW_Result> IHD_CANDIDATEJOURNAL_VIEW(Nullable<long> rid, Nullable<long> v4rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            var v4ridParameter = v4rid.HasValue ?
                new ObjectParameter("v4rid", v4rid) :
                new ObjectParameter("v4rid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_CANDIDATEJOURNAL_VIEW_Result>("IHD_CANDIDATEJOURNAL_VIEW", ridParameter, v4ridParameter);
        }
    
        public virtual ObjectResult<IHDcandidatejournal_Result> IHDcandidatejournal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHDcandidatejournal_Result>("IHDcandidatejournal");
        }
    }
}
