//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LIVEDBEntities7 : DbContext
    {
        public LIVEDBEntities7()
            : base("name=LIVEDBEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HC_USERS> HC_USERS { get; set; }
        public virtual DbSet<HCM_LOCATIONS> HCM_LOCATIONS { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> Recruiter_details(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Recruiter_details", useridParameter);
        }
    
        public virtual int RecruiterTracking_data(Nullable<long> userid, string id, string name, Nullable<decimal> gP, string gPM, string clientname)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var gPParameter = gP.HasValue ?
                new ObjectParameter("GP", gP) :
                new ObjectParameter("GP", typeof(decimal));
    
            var gPMParameter = gPM != null ?
                new ObjectParameter("GPM", gPM) :
                new ObjectParameter("GPM", typeof(string));
    
            var clientnameParameter = clientname != null ?
                new ObjectParameter("clientname", clientname) :
                new ObjectParameter("clientname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RecruiterTracking_data", useridParameter, idParameter, nameParameter, gPParameter, gPMParameter, clientnameParameter);
        }
    
        public virtual int RecruiterTracking_insert_data(Nullable<long> userid, string id, string name, Nullable<decimal> gP, string gPM)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var gPParameter = gP.HasValue ?
                new ObjectParameter("GP", gP) :
                new ObjectParameter("GP", typeof(decimal));
    
            var gPMParameter = gPM != null ?
                new ObjectParameter("GPM", gPM) :
                new ObjectParameter("GPM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RecruiterTracking_insert_data", useridParameter, idParameter, nameParameter, gPParameter, gPMParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RecrutierCandidateTrackingCountActive(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RecrutierCandidateTrackingCountActive", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RecrutierCandidateTrackingCountFTE(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RecrutierCandidateTrackingCountFTE", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RecrutierCandidateTrackingCountInActive(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RecrutierCandidateTrackingCountInActive", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RecrutierCandidateTrackingCountPermanant(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RecrutierCandidateTrackingCountPermanant", useridParameter);
        }
    
        public virtual ObjectResult<RecrutierCandidateTrackingDetails_Result> RecrutierCandidateTrackingDetails(string username, string employeeno)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var employeenoParameter = employeeno != null ?
                new ObjectParameter("employeeno", employeeno) :
                new ObjectParameter("employeeno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecrutierCandidateTrackingDetails_Result>("RecrutierCandidateTrackingDetails", usernameParameter, employeenoParameter);
        }
    
        public virtual ObjectResult<RecrutierTrackingSystem_Result> RecrutierTrackingSystem(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecrutierTrackingSystem_Result>("RecrutierTrackingSystem", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Recruiter_details_1(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Recruiter_details_1", useridParameter);
        }
    }
}
