//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_RESUME_DOCUMENTS
    {
        public long RID { get; set; }
        public Nullable<long> ResID { get; set; }
        public string Description { get; set; }
        public long TID { get; set; }
        public string FileData { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string ResHTMLText { get; set; }
        public Nullable<long> FileSize { get; set; }
        public long ReqResID { get; set; }
        public string ResConvertedText { get; set; }
        public short ConvertDocMigration { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> V3V4RID { get; set; }
        public string IsMigrated { get; set; }
        public byte[] V4FileData { get; set; }
    }
}
