//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_USERS
    {
        public long RID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public short Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public long DivisionID { get; set; }
        public long LocationID { get; set; }
        public long RightsID { get; set; }
        public long Status { get; set; }
        public string EncKey { get; set; }
        public string EncVec { get; set; }
        public string EmailID { get; set; }
        public string Mobile { get; set; }
        public long TeamID { get; set; }
        public long AccessRights { get; set; }
        public long ReportsTo { get; set; }
        public string ResourceCost { get; set; }
        public string AccessLevel { get; set; }
        public string UserXML1 { get; set; }
        public string Notes { get; set; }
        public string AccessQuery { get; set; }
        public byte[] MailSignature { get; set; }
        public short AccessType { get; set; }
        public short ISRecruiter { get; set; }
        public short ISTeamLeader { get; set; }
        public short ISOpManager { get; set; }
        public short ISBuManager { get; set; }
        public short ISHRManager { get; set; }
        public short ISTopManager { get; set; }
        public short ISPartner { get; set; }
        public short InProcessNotification { get; set; }
        public short ResumeNotification { get; set; }
        public short BlockedResumeNotification { get; set; }
        public long HCUserID { get; set; }
        public byte[] RLTS { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<System.DateTime> NA_TS { get; set; }
        public Nullable<System.DateTime> RL_TS { get; set; }
        public Nullable<System.DateTime> HL_TS { get; set; }
        public Nullable<System.DateTime> EDU_TS { get; set; }
        public Nullable<System.DateTime> FA_TS { get; set; }
        public Nullable<System.DateTime> IT_TS { get; set; }
        public Nullable<System.DateTime> JT_TS { get; set; }
        public Nullable<System.DateTime> ST_TS { get; set; }
        public Nullable<System.DateTime> SF_TS { get; set; }
        public Nullable<System.DateTime> PA_TS { get; set; }
        public Nullable<System.DateTime> HU_TS { get; set; }
        public Nullable<System.DateTime> HC_TS { get; set; }
        public short NewReqCheck { get; set; }
        public short ISSale { get; set; }
        public short ISContactConf { get; set; }
        public long CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public short ManageUnassignedResume { get; set; }
        public long V3JobsUserID { get; set; }
        public byte[] Document { get; set; }
        public Nullable<System.DateTime> LastPasswordExpiryDate { get; set; }
        public string ADSUserID { get; set; }
        public short InprocessNotificationtoOthers { get; set; }
        public string JobTitle2 { get; set; }
        public short EnableMACCheck { get; set; }
        public short ISInduction { get; set; }
        public long RVendorID { get; set; }
        public long DesignLayout { get; set; }
        public long SearchDesignLayout { get; set; }
        public long ResumeDesignLayout { get; set; }
        public long OfferDesignLayout { get; set; }
        public short MarkAsSignatoryUser { get; set; }
        public string ImageName { get; set; }
        public byte[] ImgPhoto { get; set; }
        public long QCManagerDesignLayout { get; set; }
        public short LanguageType { get; set; }
        public long ModifiedUserID { get; set; }
        public long IntSchedulerDesignLayout { get; set; }
        public long HRInterviewDesignLayout { get; set; }
        public byte[] PFXFileData { get; set; }
        public long DesignLayoutTemplateID { get; set; }
        public short ChkLatestMail { get; set; }
        public Nullable<System.DateTime> INT_TS { get; set; }
        public Nullable<System.DateTime> UNI_TS { get; set; }
        public Nullable<System.DateTime> SKL_TS { get; set; }
        public byte[] EncKeyAsBytes { get; set; }
        public byte[] EncVecAsBytes { get; set; }
        public short HCMSyncStatus { get; set; }
        public Nullable<System.DateTime> CLICON_TS { get; set; }
        public Nullable<System.DateTime> CLI_TS { get; set; }
        public Nullable<System.DateTime> EMP_TS { get; set; }
        public long HealthMeterID { get; set; }
        public string ReqQuery { get; set; }
        public short Is_HCAdmin { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public short Is_PortalParser { get; set; }
        public Nullable<System.DateTime> LastFailedAttempt { get; set; }
        public int LastFailedAttemptCnt { get; set; }
        public short Is_QCAuditMgr2 { get; set; }
        public string EmployeeID { get; set; }
        public short Is_ERSuperManager { get; set; }
        public short Is_OperationsSuperManager { get; set; }
        public short Is_AuditSuperManager { get; set; }
        public short Is_GlobalManager { get; set; }
        public long OperationMgrGrpID { get; set; }
        public long AuditMgrGrpID { get; set; }
        public Nullable<short> CanUserAccessPOExtention { get; set; }
        public short ROOprSMgr { get; set; }
        public long RecruiterHead { get; set; }
        public long HRHead { get; set; }
        public long InvoiceLocID { get; set; }
        public long FTEOperationMgrGrpID { get; set; }
        public long FTEAuditMgrGrpID { get; set; }
        public long PermOperationMgrGrpID { get; set; }
        public long PermAuditMgrGrpID { get; set; }
        public long JoiningRemaindersDesignLayout { get; set; }
        public Nullable<long> V5RID { get; set; }
        public string pswd { get; set; }
    }
}
