//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_LOCATIONS
    {
        public long RID { get; set; }
        public string LocationTitle { get; set; }
        public long RegionID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public long UserID { get; set; }
        public string RefID { get; set; }
        public long MCreatedUser { get; set; }
        public System.DateTime MCreatedDate { get; set; }
        public long MModifiedUser { get; set; }
        public long GSTStateID { get; set; }
        public string GSTNo { get; set; }
        public string GSTAddress { get; set; }
    }
}
