//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHD_COSEARCH_REPORT
    {
        public long Rid { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> Counts { get; set; }
        public Nullable<System.DateTime> LOGINDate { get; set; }
        public string LOGINtimestr { get; set; }
        public string IPAddress { get; set; }
    }
}
