//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHD_CO_SEARCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHD_CO_SEARCH()
        {
            this.IHD_CO_SEARCH_VIEW = new HashSet<IHD_CO_SEARCH_VIEW>();
        }
    
        public long Rid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> PhoneNo { get; set; }
        public string EmailID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHD_CO_SEARCH_VIEW> IHD_CO_SEARCH_VIEW { get; set; }
    }
}
