//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHD_CO_SEARCH_VIEW
    {
        public long Rid { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> CORID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Comments { get; set; }
    
        public virtual IHD_CO_SEARCH IHD_CO_SEARCH { get; set; }
    }
}
